### PR TITLE
193-Updated Kube Helm templates to include option of enabling HPA

### PR DESCRIPTION
**Pull request by dtadcox**

### CODE REVIEW

**Comment by katheris** [comment]
@dtadcox two things, one you need to update the tests and add tests for HPA, secondly it looks like the changes you have made will result in the HPA pieces always being added, is this your intention or would it be better to have some sort of flag that causes the new pieces to appear in generation?

**Comment by ibmcloudtools** [comment]
Please open PRs against development branch.

**Comment by dtadcox** [comment]
@katheris in regards 'always on' question, the only part of this that is always on is the specification of a target cpu and memory metric.  Those targets shouldn't impact the user's runtime experience, unless they enable HPA.  HPA is gated by a boolean in the values, so by default it should be off.  If we gate the metrics in the deployment.yaml, then other features that may want to use those metrics might miss them unless they turn on HPA.  

As for the testing of this capability, I might need a bit of guidance on the test framework.  I'll poke around, but I think a bit of guidance would be helpful.  Thanks!

**Comment by katheris** [comment]
@dtadcox so you are happy for these changes to be included in the files even for Spring, Swift, Node and Python applications? For the tests if you take a look here: https://github.com/ibm-developer/generator-ibm-cloud-enablement/blob/master/test/test-kubernetes.js#L55 you can see a test that checks whether the deployment.yaml files is created, you can also verify that it has particular content using `assert.fileContent('location of file', 'contents to check for')` Full documentation for the framework used is here: http://yeoman.io/authoring/testing.html

**Comment by dtadcox** [comment]
@katheris In regards the target metrics we've provided, they are simply ballpark numbers for defaults.  If you have any thoughts on varying them by app platform, I'm open to suggestion, but short of that, I'm hopeful they are a good place to start.  So, beyond that, nothing else should be impacted by the app platform.  

Thanks for the pointers on the testing side, I'll need to digest that some.

**Comment by dtadcox** [comment]
@katheris I've added some test cases to verify the helm template changes included in this pull request.  In the process of testing, I found there are other 'related' template files that I believe needed touching.  So, the new change set does that.  Please confirm that the template files under the ../java directory also need editing.  I've added the hpa.yaml file to the index.js file, so it is pulled into the generated helm.  In that same file, I fixed a tabbing issue that I found from a previous edit.  One question, I'd like to add a test or two for the deployment file changes I've made, but I'm having some issues visualizing a check for those values using the assertYmlContent call.  Where is this call documented?  Is there a related check that simply allows me to validate the existence of a value?

**Comment by katheris** [comment]
@dtadcox The java templates do need update yes, the updates you have look good. The assertYmlContent call is just a function that I set up to get error messages clearly identifying what failed:
```
 function assertYmlContent(actual, expected, label) {
 	assert.strictEqual(actual, expected, 'Expected ' + label + ' to be ' + expected + ', found ' + actual);
}
```
For assertions you can use any of the Yeoman asserts: https://github.com/yeoman/yeoman-assert or any of the base node asserts:  https://nodejs.org/api/assert.html

**Comment by dtadcox** [comment]
@katheris Thanks for the pointers.  Sorry, I missed that the assertYmlContent was a local method.  With your clarification, I've added to the concept by creating a 'assert exists' style method.  My latest change set is more or less complete, if you'd like to take a look.  Of course, per our conversation this morning, all of this is pending an investigation into how it will impact Armada.  But, if possible, it would be good to get your sign-off on the content, as is, pending that investigation.  Thanks!

**Pull request closed without merging**
