### PR TITLE
Refactored Dockerfile template

### PR DESCRIPTION
**Pull request by Rachelwrq**
Modified the file to contain a [link](https://github.com/WASdev/ci.docker#enterprise-functionality) to the enterprise QoS. Changed the command to `RUN config.sh` in the end.

### CODE REVIEW

**Comment by arthurdm** [comment]
hi @jkingoliver - do you know who would be the best person to review this PR?

**Comment by jkingoliver** [comment]
@Rachelwrq Should there be a new file called `configure.sh` that contains the scripts removed from Dockerfile?

**Comment by arthurdm** [comment]
hi @jkingoliver - that script is built into the base WebSphere Liberty and put into the image's path, so it can be easily invoked via `configure.sh`.  Here's the location in our GitHub repo:  https://github.com/WASdev/ci.docker/blob/master/ga/19.0.0.3/kernel/helpers/build/configure.sh

**Comment by christiancompton** [comment]
Closing, reopen if needed.

**Pull request closed without merging**
