### PR TITLE
fix: update the liberty dc to 2018.4.1

### PR DESCRIPTION
**Pull request by shiyanf**
In this release, we have removed the native library, so fixed the issue #412.

### CODE REVIEW

**Comment by paulben** [comment]
Hi @shiyanf . I see you have restored the app metrics install. That was just intentionally removed by @NottyCode. Have you checked with him on restoring it?

**Comment by shiyanf** [comment]
@paulben @NottyCode remove this liberty dc as this issue https://github.com/ibm-developer/generator-ibm-cloud-enablement/issues/412. But we have fixed this issue in this new dc release.  So I think we can add it back.

**Comment by NottyCode** [comment]
Output:

Step 8/10 : RUN /opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh -silent
 ---> Running in 90df722e72ef
The Liberty data collector home is /opt/ibm/wlp/usr/extension/liberty_dc.

The Liberty home directory is /opt/ibm/wlp.


The JAVA_HOME variable is set to /opt/ibm/java/jre.

Server type is set to ICAM. Config package is /opt/ibm-cloud-apm-clouddc-configpack.tar.

Configuring the Liberty server defaultServer...
The server defaultServer is configured for the first time...

Modifying server.xml finished.
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 690: jvm.options: Permission denied
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 692: jvm.options: Permission denied
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 693: jvm.options: Permission denied
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 694: jvm.options: Permission denied
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 697: jvm.options: Permission denied
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 698: jvm.options: Permission denied
/opt/ibm/wlp/usr/extension/liberty_dc/bin/config_unified_dc.sh: line 800: jvm.options: Permission denied
JVM maxmium memory size (-Xmx) in jvm.options is set to 768M.
Modifying jvm.options finished.

Successfully configured data collector for server defaultServer.
The application server defaultServer must be restarted for configuration to take effect.

**Comment by gadekarl** [comment]
@NottyCode My response inline.

Is IBM App Metrics just a new name for what was previously known as APM Data Collector? 
>> Yes but this data collector has more capabilities to route the data to new IBM Cloud App Management server.

Has the effect of this change been tested on x86, p and z? I suspect not because when I ran it I get permission errors running the setup script. 
>> No we haven't tested it on p and z.

This creates an unnecessary number of layers the two run commands should be one.
>> agree
Please explain why this needs to be enabled. It was removed in the past because it didn't work and no one knew why this was being added.
>> It helps our customers route the data to  IBM Cloud App Management server without the customer requiring them to change their container image. It depends partially on JavaMetrics, mpMetrics but has more data. Even though it's rolled in, it won't get activated UNLESS customer gives IBM Cloud App Management server configuration info. If the IBM Cloud App Management server is not available, it will remain in disabled state. 

The main value to customer would be the ability to monitor their polyglot applications deployed in cloud, on-premise etc using IBM Cloud App Management server. 

Shall we re-submit the pull request once we test it on p and z if you are ok with above justification.

**Comment by shiyanf** [comment]
@NottyCode I have try to create a java project with microclimate 18.12, but the java project failed to build docker image. The project type is "MicroProfile / Java EE". Please help to have a look. Thanks.

```
[root@cn-lwdc-11 libertymc1]# docker build -t libertymicro:v1 .
Sending build context to Docker daemon  283.1kB
Step 1/11 : FROM websphere-liberty:webProfile7
 ---> 674f3d25cb76
Step 2/11 : LABEL maintainer="IBM Java Engineering at IBM Cloud"
 ---> Using cache
 ---> f84debe0aecc
Step 3/11 : COPY /target/liberty/wlp/usr/servers/defaultServer /config/
COPY failed: stat /var/lib/docker/tmp/docker-builder964182177/target/liberty/wlp/usr/servers/defaultServer: no such file or directory

```

**Comment by HuiHGao** [comment]
@NottyCode , I want to do a testing with for the zlinux and plinux, what steps do you suggest? Install the microcimate and generate the dockerfile, then run the docker in zlinux/plinux? thanks!

**Comment by christiancompton** [comment]
Closing - please reopen if needed.

**Pull request closed without merging**
