### PR TITLE
fix(templates): use {{{ }}} to esacpe special characters

### PR DESCRIPTION
**Pull request by Aerex**

### CODE REVIEW

**Comment by ebullient** [comment]
This is not the correct way to achieve the fix for the problem. The answer is in altering the behavior here: https://github.com/ibm-developer/generator-ibm-cloud-enablement/blob/master/generators/lib/helpers.js

{{tag ... }} is a special helper that preserves the {{ and }} at the end (required for helm charts).

**Comment by katheris** [comment]
Also @Aerex where are the tests to verify this change?

**Comment by katheris** [comment]
As Erin states there is no need to escape every single one, the line that comes out incorrectly is `{{tag ' if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "8") '}}` due to the double quotes, so we can simply update that one

**Comment by katheris** [comment]
Closing as have opened PR #208 instead

**Pull request closed without merging**
