### PR TITLE
chore: Merging CHANGELOG and package.json changes

### PR DESCRIPTION
**Pull request by mfpanaly**

### CODE REVIEW

**Comment by EnriqueL8** [comment]
Hey @quanvo87, this PR upgrade the version in npm to `0.13.0` but tagged the repo to `0.12.1`. So it produced an inconsistency between the versions in npm and github... I believe this happened because after this PR was generated , a new commit was push to update the `Package.json` to `0.13.0`. Could we look to fix this?

**Comment by quanvo87** [comment]
@EnriqueL8 Correct, sorry about that. I wanted to change the PR to be a minor version bump instead of patch, but what I tried only changed the NPM versioning. It looks like things are sorted out now. Thanks @ebullient

**Comment by EnriqueL8** [comment]
Hey @quanvo87, FYI in order to make a minor version bump in your PR to master the header needs to have the format `feat():`, since your [PR](https://github.com/ibm-developer/generator-ibm-cloud-enablement/pull/240) had `fix():` is was a patch . The github repo runs a travis build to tag to the next version when a PR is merged to master with one of those key words. For example [here](https://travis-ci.org/ibm-developer/generator-ibm-cloud-enablement/builds/358880354#L2491)

**Comment by quanvo87** [comment]
Thanks, @EnriqueL8 !

**Pull request merged**
